import '../../src/iconfont_data.dart';
import '../../src/utils.dart';

class IconTemplate {
  static String build(String className, IconFontData data) {
    var itemContent = data.glyphs
        .map((e) => _buildItem(e, data.fontPackage ?? ""))
        .join("\n");
    final previewIconContent =
        data.glyphs.map((e) => _buildPreviewIcon(e, className)).join("\n");

    var fontPackageContent = (data.fontPackage ?? "").isNotEmpty
        ? "\n  static const String _package = '${data.fontPackage}';"
        : "";

    String contents =
        '''
//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class $className {
  static const String _family = '${data.fontFamily}';$fontPackageContent
  
  $className._();
  
$itemContent
}

''';

    return contents;
  }

  static String _buildItem(IconFontGlyph glyphs, String fontPackage) {
    String iconName = Utils.snake("${glyphs.fontClass}");
    String unicode = glyphs.unicode ?? "";
    String comment = "";
    String packageName = "";
    if (glyphs.name != null && glyphs.name != "") {
      comment = " // ${glyphs.name}";
    }

    if (fontPackage.isNotEmpty) {
      packageName = ", fontPackage: _package";
    }

    return '''  static const IconData $iconName = IconData(0x$unicode, fontFamily: _family$packageName);$comment''';
  }

  static String _buildPreviewIcon(IconFontGlyph glyphs, String iconClass) {
    String iconName = Utils.snake("${glyphs.fontClass}");

    return '''    _PreviewIcon($iconClass.$iconName, "$iconName", "${glyphs.name}"),''';
  }
}
