//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class FlightBookingAPPIconfont {
  static const String _family = 'FlightBookingAPPIconfont';
  
  FlightBookingAPPIconfont._();
  
  static const IconData bz_flight_o = IconData(0xe678, fontFamily: _family); // bz-flight-36-o
}

